QT += testlib widgets network

CONFIG += qt console warn_on depend_includepath testcase
CONFIG -= app_bundle

TEMPLATE = app

SOURCES +=  \
    ../../VNA_embedded/Application/Communication/Protocol.cpp \
    ../LibreVNA-GUI/Calibration/LibreCAL/caldevice.cpp \
    ../LibreVNA-GUI/Calibration/LibreCAL/librecaldialog.cpp \
    ../LibreVNA-GUI/Calibration/LibreCAL/usbdevice.cpp \
    ../LibreVNA-GUI/Calibration/calibration.cpp \
    ../LibreVNA-GUI/Calibration/calibrationmeasurement.cpp \
    ../LibreVNA-GUI/Calibration/calkit.cpp \
    ../LibreVNA-GUI/Calibration/calkitdialog.cpp \
    ../LibreVNA-GUI/Calibration/calstandard.cpp \
    ../LibreVNA-GUI/Calibration/manualcalibrationdialog.cpp \
    ../LibreVNA-GUI/CustomWidgets/colorpickerbutton.cpp \
    ../LibreVNA-GUI/CustomWidgets/csvimport.cpp \
    ../LibreVNA-GUI/CustomWidgets/informationbox.cpp \
    ../LibreVNA-GUI/CustomWidgets/jsonpickerdialog.cpp \
    ../LibreVNA-GUI/CustomWidgets/siunitedit.cpp \
    ../LibreVNA-GUI/CustomWidgets/tilewidget.cpp \
    ../LibreVNA-GUI/CustomWidgets/toggleswitch.cpp \
    ../LibreVNA-GUI/CustomWidgets/touchstoneimport.cpp \
    ../LibreVNA-GUI/CustomWidgets/tracesetselector.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/amplitudecaldialog.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogv1.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogvfe.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogvff.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/firmwareupdatedialog.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/frequencycaldialog.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/librevnadriver.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/librevnatcpdriver.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/librevnausbdriver.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogV1.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogvfe.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogvff.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/receivercaldialog.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/sourcecaldialog.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddevice.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddriver.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddeviceeditdialog.cpp \
    ../LibreVNA-GUI/Device/SSA3000X/ssa3000xdriver.cpp \
    ../LibreVNA-GUI/Device/SNA5000A/sna5000adriver.cpp \
    ../LibreVNA-GUI/Device/devicedriver.cpp \
    ../LibreVNA-GUI/Device/devicelog.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/devicepacketlog.cpp \
    ../LibreVNA-GUI/Device/LibreVNA/devicepacketlogview.cpp \
    ../LibreVNA-GUI/Device/devicetcpdriver.cpp \
    ../LibreVNA-GUI/Generator/generator.cpp \
    ../LibreVNA-GUI/Generator/signalgenwidget.cpp \
    ../LibreVNA-GUI/SpectrumAnalyzer/spectrumanalyzer.cpp \
    ../LibreVNA-GUI/SpectrumAnalyzer/tracewidgetsa.cpp \
    ../LibreVNA-GUI/Tools/eseries.cpp \
    ../LibreVNA-GUI/Tools/impedancematchdialog.cpp \
    ../LibreVNA-GUI/Tools/mixedmodeconversion.cpp \
    ../LibreVNA-GUI/Tools/parameters.cpp \
    ../LibreVNA-GUI/Traces/Marker/marker.cpp \
    ../LibreVNA-GUI/Traces/Marker/markergroup.cpp \
    ../LibreVNA-GUI/Traces/Marker/markermodel.cpp \
    ../LibreVNA-GUI/Traces/Marker/markerwidget.cpp \
    ../LibreVNA-GUI/Traces/Math/dft.cpp \
    ../LibreVNA-GUI/Traces/Math/expression.cpp \
    ../LibreVNA-GUI/Traces/Math/medianfilter.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpError.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncCmplx.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncCommon.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncMatrix.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncNonCmplx.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncStr.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpICallback.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpIOprt.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpIPackage.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpIToken.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpIValReader.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpIValue.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpIfThenElse.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtBinAssign.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtBinCommon.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtCmplx.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtIndex.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtMatrix.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtNonCmplx.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtPostfixCommon.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageCmplx.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageCommon.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageMatrix.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageNonCmplx.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageStr.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageUnit.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpParser.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpParserBase.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpParserMessageProvider.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpRPN.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpScriptTokens.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpTest.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpTokenReader.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpValReader.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpValue.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpValueCache.cpp \
    ../LibreVNA-GUI/Traces/Math/parser/mpVariable.cpp \
    ../LibreVNA-GUI/Traces/Math/tdr.cpp \
    ../LibreVNA-GUI/Traces/Math/timegate.cpp \
    ../LibreVNA-GUI/Traces/Math/tracemath.cpp \
    ../LibreVNA-GUI/Traces/Math/windowfunction.cpp \
    ../LibreVNA-GUI/Traces/eyediagramplot.cpp \
    ../LibreVNA-GUI/Traces/fftcomplex.cpp \
    ../LibreVNA-GUI/Traces/sparamtraceselector.cpp \
    ../LibreVNA-GUI/Traces/trace.cpp \
    ../LibreVNA-GUI/Traces/traceaxis.cpp \
    ../LibreVNA-GUI/Traces/tracecsvexport.cpp \
    ../LibreVNA-GUI/Traces/traceeditdialog.cpp \
    ../LibreVNA-GUI/Traces/traceimportdialog.cpp \
    ../LibreVNA-GUI/Traces/tracemodel.cpp \
    ../LibreVNA-GUI/Traces/traceplot.cpp \
    ../LibreVNA-GUI/Traces/tracepolar.cpp \
    ../LibreVNA-GUI/Traces/tracepolarchart.cpp \
    ../LibreVNA-GUI/Traces/tracesmithchart.cpp \
    ../LibreVNA-GUI/Traces/tracetouchstoneexport.cpp \
    ../LibreVNA-GUI/Traces/tracewaterfall.cpp \
    ../LibreVNA-GUI/Traces/tracewidget.cpp \
    ../LibreVNA-GUI/Traces/tracexyplot.cpp \
    ../LibreVNA-GUI/Traces/waterfallaxisdialog.cpp \
    ../LibreVNA-GUI/Traces/xyplotaxisdialog.cpp \
    ../LibreVNA-GUI/Util/QMicroz/miniz.c \
    ../LibreVNA-GUI/Util/QMicroz/qmicroz.cpp \
    ../LibreVNA-GUI/Util/QMicroz/tools.cpp \
    ../LibreVNA-GUI/Util/prbs.cpp \
    ../LibreVNA-GUI/Util/util.cpp \
    ../LibreVNA-GUI/Util/usbinbuffer.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/deembedding.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/deembeddingdialog.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/deembeddingoption.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/impedancerenormalization.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/manualdeembeddingdialog.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/matchingnetwork.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/portextension.cpp \
    ../LibreVNA-GUI/VNA/Deembedding/twothru.cpp \
    ../LibreVNA-GUI/VNA/tracewidgetvna.cpp \
    ../LibreVNA-GUI/VNA/vna.cpp \
    ../LibreVNA-GUI/about.cpp \
    ../LibreVNA-GUI/appwindow.cpp \
    ../LibreVNA-GUI/averaging.cpp \
    ../LibreVNA-GUI/csv.cpp \
    ../LibreVNA-GUI/mode.cpp \
    ../LibreVNA-GUI/modehandler.cpp \
    ../LibreVNA-GUI/modewindow.cpp \
    ../LibreVNA-GUI/preferences.cpp \
    ../LibreVNA-GUI/savable.cpp \
    ../LibreVNA-GUI/scpi.cpp \
    ../LibreVNA-GUI/tcpserver.cpp \
    ../LibreVNA-GUI/streamingserver.cpp \
    ../LibreVNA-GUI/touchstone.cpp \
    ../LibreVNA-GUI/unit.cpp \
    ffttests.cpp \
    impedancerenormalizationtests.cpp \
    main.cpp \
    parametertests.cpp \
    portextensiontests.cpp \
    utiltests.cpp

HEADERS += \
    ../../VNA_embedded/Application/Communication/Protocol.hpp \
    ../LibreVNA-GUI/Calibration/Eigen/Cholesky \
    ../LibreVNA-GUI/Calibration/Eigen/CholmodSupport \
    ../LibreVNA-GUI/Calibration/Eigen/Core \
    ../LibreVNA-GUI/Calibration/Eigen/Dense \
    ../LibreVNA-GUI/Calibration/Eigen/Eigen \
    ../LibreVNA-GUI/Calibration/Eigen/Eigenvalues \
    ../LibreVNA-GUI/Calibration/Eigen/Geometry \
    ../LibreVNA-GUI/Calibration/Eigen/Householder \
    ../LibreVNA-GUI/Calibration/Eigen/IterativeLinearSolvers \
    ../LibreVNA-GUI/Calibration/Eigen/Jacobi \
    ../LibreVNA-GUI/Calibration/Eigen/KLUSupport \
    ../LibreVNA-GUI/Calibration/Eigen/LU \
    ../LibreVNA-GUI/Calibration/Eigen/MetisSupport \
    ../LibreVNA-GUI/Calibration/Eigen/OrderingMethods \
    ../LibreVNA-GUI/Calibration/Eigen/PaStiXSupport \
    ../LibreVNA-GUI/Calibration/Eigen/PardisoSupport \
    ../LibreVNA-GUI/Calibration/Eigen/QR \
    ../LibreVNA-GUI/Calibration/Eigen/QtAlignedMalloc \
    ../LibreVNA-GUI/Calibration/Eigen/SPQRSupport \
    ../LibreVNA-GUI/Calibration/Eigen/SVD \
    ../LibreVNA-GUI/Calibration/Eigen/Sparse \
    ../LibreVNA-GUI/Calibration/Eigen/SparseCholesky \
    ../LibreVNA-GUI/Calibration/Eigen/SparseCore \
    ../LibreVNA-GUI/Calibration/Eigen/SparseLU \
    ../LibreVNA-GUI/Calibration/Eigen/SparseQR \
    ../LibreVNA-GUI/Calibration/Eigen/StdDeque \
    ../LibreVNA-GUI/Calibration/Eigen/StdList \
    ../LibreVNA-GUI/Calibration/Eigen/StdVector \
    ../LibreVNA-GUI/Calibration/Eigen/SuperLUSupport \
    ../LibreVNA-GUI/Calibration/Eigen/UmfPackSupport \
    ../LibreVNA-GUI/Calibration/LibreCAL/caldevice.h \
    ../LibreVNA-GUI/Calibration/LibreCAL/librecaldialog.h \
    ../LibreVNA-GUI/Calibration/LibreCAL/usbdevice.h \
    ../LibreVNA-GUI/Calibration/calibration.h \
    ../LibreVNA-GUI/Calibration/calibrationmeasurement.h \
    ../LibreVNA-GUI/Calibration/calkit.h \
    ../LibreVNA-GUI/Calibration/calkitdialog.h \
    ../LibreVNA-GUI/Calibration/calstandard.h \
    ../LibreVNA-GUI/Calibration/manualcalibrationdialog.h \
    ../LibreVNA-GUI/CustomWidgets/colorpickerbutton.h \
    ../LibreVNA-GUI/CustomWidgets/csvimport.h \
    ../LibreVNA-GUI/CustomWidgets/informationbox.h \
    ../LibreVNA-GUI/CustomWidgets/jsonpickerdialog.h \
    ../LibreVNA-GUI/CustomWidgets/siunitedit.h \
    ../LibreVNA-GUI/CustomWidgets/tilewidget.h \
    ../LibreVNA-GUI/CustomWidgets/toggleswitch.h \
    ../LibreVNA-GUI/CustomWidgets/touchstoneimport.h \
    ../LibreVNA-GUI/CustomWidgets/tracesetselector.h \
    ../LibreVNA-GUI/Device/LibreVNA/amplitudecaldialog.h \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogv1.h \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogvfe.h \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogvff.h \
    ../LibreVNA-GUI/Device/LibreVNA/firmwareupdatedialog.h \
    ../LibreVNA-GUI/Device/LibreVNA/frequencycaldialog.h \
    ../LibreVNA-GUI/Device/LibreVNA/librevnadriver.h \
    ../LibreVNA-GUI/Device/LibreVNA/librevnatcpdriver.h \
    ../LibreVNA-GUI/Device/LibreVNA/librevnausbdriver.h \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogV1.h \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogvfe.h \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogvff.h \
    ../LibreVNA-GUI/Device/LibreVNA/receivercaldialog.h \
    ../LibreVNA-GUI/Device/LibreVNA/sourcecaldialog.h \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddevice.h \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddriver.h \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddeviceeditdialog.h \
    ../LibreVNA-GUI/Device/SSA3000X/ssa3000xdriver.h \
    ../LibreVNA-GUI/Device/SNA5000A/sna5000adriver.h \
    ../LibreVNA-GUI/Device/devicedriver.h \
    ../LibreVNA-GUI/Device/devicelog.h \
    ../LibreVNA-GUI/Device/LibreVNA/devicepacketlog.h \
    ../LibreVNA-GUI/Device/LibreVNA/devicepacketlogview.h \
    ../LibreVNA-GUI/Device/devicetcpdriver.h \
    ../LibreVNA-GUI/Generator/generator.h \
    ../LibreVNA-GUI/Generator/signalgenwidget.h \
    ../LibreVNA-GUI/SpectrumAnalyzer/spectrumanalyzer.h \
    ../LibreVNA-GUI/SpectrumAnalyzer/tracewidgetsa.h \
    ../LibreVNA-GUI/Tools/eseries.h \
    ../LibreVNA-GUI/Tools/impedancematchdialog.h \
    ../LibreVNA-GUI/Tools/mixedmodeconversion.h \
    ../LibreVNA-GUI/Tools/parameters.h \
    ../LibreVNA-GUI/Traces/Marker/marker.h \
    ../LibreVNA-GUI/Traces/Marker/markergroup.h \
    ../LibreVNA-GUI/Traces/Marker/markermodel.h \
    ../LibreVNA-GUI/Traces/Marker/markerwidget.h \
    ../LibreVNA-GUI/Traces/Math/dft.h \
    ../LibreVNA-GUI/Traces/Math/expression.h \
    ../LibreVNA-GUI/Traces/Math/medianfilter.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpCompat.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpDefines.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpError.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncCmplx.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncCommon.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncMatrix.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncNonCmplx.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpFuncStr.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpFwdDecl.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpICallback.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpIOprt.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpIPackage.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpIPrecedence.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpIToken.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpIValReader.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpIValue.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpIfThenElse.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpMatrix.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpMatrixError.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtBinAssign.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtBinCommon.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtCmplx.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtIndex.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtMatrix.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtNonCmplx.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpOprtPostfixCommon.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageCmplx.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageCommon.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageMatrix.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageNonCmplx.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageStr.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpPackageUnit.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpParser.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpParserBase.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpParserMessageProvider.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpRPN.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpScriptTokens.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpStack.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpTest.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpTokenReader.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpTypes.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpValReader.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpValue.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpValueCache.h \
    ../LibreVNA-GUI/Traces/Math/parser/mpVariable.h \
    ../LibreVNA-GUI/Traces/Math/parser/suSortPred.h \
    ../LibreVNA-GUI/Traces/Math/parser/suStringTokens.h \
    ../LibreVNA-GUI/Traces/Math/parser/utGeneric.h \
    ../LibreVNA-GUI/Traces/Math/tdr.h \
    ../LibreVNA-GUI/Traces/Math/timegate.h \
    ../LibreVNA-GUI/Traces/Math/tracemath.h \
    ../LibreVNA-GUI/Traces/Math/windowfunction.h \
    ../LibreVNA-GUI/Traces/eyediagramplot.h \
    ../LibreVNA-GUI/Traces/fftcomplex.h \
    ../LibreVNA-GUI/Traces/sparamtraceselector.h \
    ../LibreVNA-GUI/Traces/trace.h \
    ../LibreVNA-GUI/Traces/traceaxis.h \
    ../LibreVNA-GUI/Traces/tracecsvexport.h \
    ../LibreVNA-GUI/Traces/traceeditdialog.h \
    ../LibreVNA-GUI/Traces/traceimportdialog.h \
    ../LibreVNA-GUI/Traces/tracemodel.h \
    ../LibreVNA-GUI/Traces/traceplot.h \
    ../LibreVNA-GUI/Traces/tracepolar.h \
    ../LibreVNA-GUI/Traces/tracepolarchart.h \
    ../LibreVNA-GUI/Traces/tracesmithchart.h \
    ../LibreVNA-GUI/Traces/tracetouchstoneexport.h \
    ../LibreVNA-GUI/Traces/tracewaterfall.h \
    ../LibreVNA-GUI/Traces/tracewidget.h \
    ../LibreVNA-GUI/Traces/tracexyplot.h \
    ../LibreVNA-GUI/Traces/waterfallaxisdialog.h \
    ../LibreVNA-GUI/Traces/xyplotaxisdialog.h \
    ../LibreVNA-GUI/Util/QMicroz/miniz.h \
    ../LibreVNA-GUI/Util/QMicroz/qmicroz.h \
    ../LibreVNA-GUI/Util/QMicroz/tools.h \
    ../LibreVNA-GUI/Util/prbs.h \
    ../LibreVNA-GUI/Util/util.h \
    ../LibreVNA-GUI/Util/usbinbuffer.h \
    ../LibreVNA-GUI/VNA/Deembedding/deembedding.h \
    ../LibreVNA-GUI/VNA/Deembedding/deembeddingdialog.h \
    ../LibreVNA-GUI/VNA/Deembedding/deembeddingoption.h \
    ../LibreVNA-GUI/VNA/Deembedding/impedancerenormalization.h \
    ../LibreVNA-GUI/VNA/Deembedding/manualdeembeddingdialog.h \
    ../LibreVNA-GUI/VNA/Deembedding/matchingnetwork.h \
    ../LibreVNA-GUI/VNA/Deembedding/portextension.h \
    ../LibreVNA-GUI/VNA/Deembedding/twothru.h \
    ../LibreVNA-GUI/VNA/tracewidgetvna.h \
    ../LibreVNA-GUI/VNA/vna.h \
    ../LibreVNA-GUI/about.h \
    ../LibreVNA-GUI/appwindow.h \
    ../LibreVNA-GUI/averaging.h \
    ../LibreVNA-GUI/csv.h \
    ../LibreVNA-GUI/json.hpp \
    ../LibreVNA-GUI/mode.h \
    ../LibreVNA-GUI/modehandler.h \
    ../LibreVNA-GUI/modewindow.h \
    ../LibreVNA-GUI/preferences.h \
    ../LibreVNA-GUI/savable.h \
    ../LibreVNA-GUI/scpi.h \
    ../LibreVNA-GUI/tcpserver.h \
    ../LibreVNA-GUI/streamingserver.h \
    ../LibreVNA-GUI/touchstone.h \
    ../LibreVNA-GUI/unit.h \
    ffttests.h \
    impedancerenormalizationtests.h \
    parametertests.h \
    portextensiontests.h \
    utiltests.h

INCLUDEPATH += \
    ../LibreVNA-GUI \
    ../LibreVNA-GUI/Util \
    ../LibreVNA-GUI/VNA/Deembedding \
    ../LibreVNA-GUI/Calibration

FORMS += \
    ../LibreVNA-GUI/Calibration/CalStandardLineEditDialog.ui \
    ../LibreVNA-GUI/Calibration/CalStandardLoadEditDialog.ui \
    ../LibreVNA-GUI/Calibration/CalStandardOpenEditDialog.ui \
    ../LibreVNA-GUI/Calibration/CalStandardReflectEditDialog.ui \
    ../LibreVNA-GUI/Calibration/CalStandardShortEditDialog.ui \
    ../LibreVNA-GUI/Calibration/CalStandardThroughEditDialog.ui \
    ../LibreVNA-GUI/Calibration/LibreCAL/factoryUpdateDialog.ui \
    ../LibreVNA-GUI/Calibration/LibreCAL/librecaldialog.ui \
    ../LibreVNA-GUI/Calibration/calibrationdialogui.ui \
    ../LibreVNA-GUI/Calibration/calkitdialog.ui \
    ../LibreVNA-GUI/Calibration/manualcalibrationdialog.ui \
    ../LibreVNA-GUI/CustomWidgets/csvimport.ui \
    ../LibreVNA-GUI/CustomWidgets/jsonpickerdialog.ui \
    ../LibreVNA-GUI/CustomWidgets/tilewidget.ui \
    ../LibreVNA-GUI/CustomWidgets/touchstoneimport.ui \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddriversettingswidget.ui \
    ../LibreVNA-GUI/Device/LibreVNA/addamplitudepointsdialog.ui \
    ../LibreVNA-GUI/Device/LibreVNA/amplitudecaldialog.ui \
    ../LibreVNA-GUI/Device/LibreVNA/automaticamplitudedialog.ui \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogv1.ui \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogvfe.ui \
    ../LibreVNA-GUI/Device/LibreVNA/deviceconfigurationdialogvff.ui \
    ../LibreVNA-GUI/Device/LibreVNA/firmwareupdatedialog.ui \
    ../LibreVNA-GUI/Device/LibreVNA/frequencycaldialog.ui \
    ../LibreVNA-GUI/Device/LibreVNA/librevnadriversettingswidget.ui \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogV1.ui \
    ../LibreVNA-GUI/Device/LibreVNA/Compound/compounddeviceeditdialog.ui \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogvfe.ui \
    ../LibreVNA-GUI/Device/LibreVNA/manualcontroldialogvff.ui \
    ../LibreVNA-GUI/Device/devicelog.ui \
    ../LibreVNA-GUI/Device/LibreVNA/devicepacketlogview.ui \
    ../LibreVNA-GUI/Device/devicetcpdriversettings.ui \
    ../LibreVNA-GUI/Generator/signalgenwidget.ui \
    ../LibreVNA-GUI/Tools/impedancematchdialog.ui \
    ../LibreVNA-GUI/Tools/mixedmodeconversion.ui \
    ../LibreVNA-GUI/Traces/Marker/markerwidget.ui \
    ../LibreVNA-GUI/Traces/Math/dftdialog.ui \
    ../LibreVNA-GUI/Traces/Math/dftexplanationwidget.ui \
    ../LibreVNA-GUI/Traces/Math/expressiondialog.ui \
    ../LibreVNA-GUI/Traces/Math/expressionexplanationwidget.ui \
    ../LibreVNA-GUI/Traces/Math/medianexplanationwidget.ui \
    ../LibreVNA-GUI/Traces/Math/medianfilterdialog.ui \
    ../LibreVNA-GUI/Traces/Math/newtracemathdialog.ui \
    ../LibreVNA-GUI/Traces/Math/tdrdialog.ui \
    ../LibreVNA-GUI/Traces/Math/tdrexplanationwidget.ui \
    ../LibreVNA-GUI/Traces/Math/timedomaingatingexplanationwidget.ui \
    ../LibreVNA-GUI/Traces/Math/timegatedialog.ui \
    ../LibreVNA-GUI/Traces/Math/timegateexplanationwidget.ui \
    ../LibreVNA-GUI/Traces/XYPlotConstantLineEditDialog.ui \
    ../LibreVNA-GUI/Traces/eyediagrameditdialog.ui \
    ../LibreVNA-GUI/Traces/polarchartdialog.ui \
    ../LibreVNA-GUI/Traces/smithchartdialog.ui \
    ../LibreVNA-GUI/Traces/tracecsvexport.ui \
    ../LibreVNA-GUI/Traces/traceeditdialog.ui \
    ../LibreVNA-GUI/Traces/traceimportdialog.ui \
    ../LibreVNA-GUI/Traces/tracetouchstoneexport.ui \
    ../LibreVNA-GUI/Traces/tracewidget.ui \
    ../LibreVNA-GUI/Traces/waterfallaxisdialog.ui \
    ../LibreVNA-GUI/Traces/xyplotaxisdialog.ui \
    ../LibreVNA-GUI/VNA/Deembedding/deembeddingdialog.ui \
    ../LibreVNA-GUI/VNA/Deembedding/impedancenormalizationdialog.ui \
    ../LibreVNA-GUI/VNA/Deembedding/manualdeembeddingdialog.ui \
    ../LibreVNA-GUI/VNA/Deembedding/matchingnetworkdialog.ui \
    ../LibreVNA-GUI/VNA/Deembedding/measurementdialog.ui \
    ../LibreVNA-GUI/VNA/Deembedding/portextensioneditdialog.ui \
    ../LibreVNA-GUI/VNA/Deembedding/twothrudialog.ui \
    ../LibreVNA-GUI/VNA/s2pImportOptions.ui \
    ../LibreVNA-GUI/aboutdialog.ui \
    ../LibreVNA-GUI/main.ui \
    ../LibreVNA-GUI/preferencesdialog.ui

CONFIG += c++17

LIBS += -lusb-1.0
unix:LIBS += -L/usr/lib/

REVISION = $$system(git rev-parse HEAD)
DEFINES += GITHASH=\\"\"$$REVISION\\"\"
DEFINES += FW_MAJOR=1 FW_MINOR=6 FW_PATCH=4 FW_SUFFIX=""#\\"\"-alpha.2\\"\"
DEFINES -= _UNICODE UNICODE
win32:DEFINES += QMICROZ_LIBRARY
