name: Lint 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1 

    - name: Install dependencies 
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
        sudo apt-get update && sudo apt-get install --no-install-recommends -y clang-format-13
    - name: Lint 
      run: |
        bash ./Software/PC_Application/Scripts/linter.sh -l --dry-run 
