M48
; DRILL file {KiCad 9.0.0} date 2025-02-25T23:13:26-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-25T23:13:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X61.109Y89.699
X66.889Y89.699
T2
X51.5Y93.0
M30
